services:

  app:
    build: .
    container_name: cloudshop-app
    ports:
      - "3000:5001"
    environment:
      DB_HOST: db
      DB_NAME: cloudshop
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: cloudshop-db
    restart: always
    environment:
      POSTGRES_DB: cloudshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
