name: Project 4 CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          npm install
          npm test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudshop-api:v1 .

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cloudshop-api:v1

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cloudshop-api:v1
            docker stop cloudshop-api || true
            docker rm cloudshop-api || true
            docker run -d -p 3000:5001 --name cloudshop-api ${{ secrets.DOCKER_USERNAME }}/cloudshop-api:v1
